/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ParkingsManagements;

import static ParkingsManagements.Konfigurasi.configDB;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPanel3 = new javax.swing.JPanel();
        labelAlliance = new javax.swing.JLabel();
        loginbutton = new javax.swing.JButton();
        Username = new javax.swing.JTextField();
        labeluser = new javax.swing.JLabel();
        labelpassword = new javax.swing.JLabel();
        Password = new javax.swing.JPasswordField();
        logo = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelAlliance.setFont(new java.awt.Font("Book Antiqua", 1, 36)); // NOI18N
        labelAlliance.setForeground(new java.awt.Color(255, 204, 51));
        labelAlliance.setText("Alliance By-Space");
        jPanel3.add(labelAlliance, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 320, 70));

        loginbutton.setBackground(new java.awt.Color(255, 204, 51));
        loginbutton.setFont(new java.awt.Font("Rockwell", 1, 11)); // NOI18N
        loginbutton.setText("LOGIN");
        loginbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbuttonActionPerformed(evt);
            }
        });
        jPanel3.add(loginbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 90, 30));

        Username.setBackground(new java.awt.Color(255, 204, 51));
        Username.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Username.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameActionPerformed(evt);
            }
        });
        jPanel3.add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 206, 38));

        labeluser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ParkingsManagements/gambar/icons8_male_user_30px_2.png"))); // NOI18N
        jPanel3.add(labeluser, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 40, 40));

        labelpassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ParkingsManagements/gambar/icons8_password_30px_2.png"))); // NOI18N
        jPanel3.add(labelpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 40, 27));

        Password.setBackground(new java.awt.Color(255, 204, 51));
        Password.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel3.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 210, 40));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ParkingsManagements/gambar/icons8_car_80px.png"))); // NOI18N
        jPanel3.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 90, 70));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ParkingsManagements/gambar/WhatsApp Image 2020-12-21 at 2.20.41 PM.jpeg"))); // NOI18N
        jPanel3.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 610));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbuttonActionPerformed
        // TODO add your handling code here:
       String username = Username.getText();
        String password = Password.getText();
        
        
        try
        {
            int log = 1;
            configDB();
       Statement st = (Statement) configDB().createStatement();
            ResultSet rs = st.executeQuery("select * from Registrations");
            
            while (rs.next())
            {
                if (rs.getString(1).equals(username)&& rs.getString(2).equals(password))
                {
                    log = 0 ;
                    break ;
                }
            }
            if (log == 0)
                JOptionPane.showMessageDialog(this, "Login Successful");
                Home pk = new Home();
                pk.setVisible(true);
           
            
        } catch (SQLException ex) {
        java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex); 
    }
    }//GEN-LAST:event_loginbuttonActionPerformed

    private void UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JPasswordField Password;
    private javax.swing.JTextField Username;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelAlliance;
    private javax.swing.JLabel labelpassword;
    private javax.swing.JLabel labeluser;
    private javax.swing.JButton loginbutton;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
